development:
   adapter: mysql2
   database: gb_development
   username: root
   password: Nus=8355030
   host: localhost

test:
   adapter: mysql2
   database: gb_test
   username: root
   password: Nus=8355030
   host: localhost

production:
   adapter: mysql2
   database: gb_production
   username: root
   password: Nus=8355030
   host: localhost
